CONFIG ?= Release
TOP_DIR = $(CURDIR)
BUILD_DIR = $(CURDIR)/build/test/$(CONFIG)

CXX = g++
CC = gcc

.PHOBY: test
test: build
	@echo "Running all test executables..."
	@for t in $(BUILD_DIR)/test_*; do \
		if [ -x $$t ]; then \
			echo "---- $$t ----"; \
			$$t || exit 1; \
		fi; \
	done
	
.PHONY: build
build:
	mkdir -p $(BUILD_DIR) && \
	cd $(BUILD_DIR) && \
	cmake -DCMAKE_BUILD_TYPE=$(CONFIG) -DCMAKE_CXX_COMPILER=$(CXX) -DCMAKE_C_COMPILER=$(CC) -DTOP_DIR=$(TOP_DIR) $(TOP_DIR)/cmake/test/ && \
	cmake --build $(BUILD_DIR) -j 6

.PHONY: remove
remove:
	rm -rf $(BUILD_DIR)

.PHONY: clean
clean:
	rm -rf build/test/

