TOP_DIR = $(CURDIR)
CMAKE_DIR = $(CURDIR)/build/external/cmake
BUILD_DIR = $(CURDIR)/build/external/

CXX = g++
CC = gcc

.PHONY: install
install:
	mkdir -p $(CMAKE_DIR) && \
	cd $(CMAKE_DIR) && \
	cmake -DCMAKE_CXX_COMPILER=$(CXX) -DCMAKE_C_COMPILER=$(CC) -DTOP_DIR=$(TOP_DIR) $(TOP_DIR)/cmake/external/ && \
	cmake --build $(CMAKE_DIR) 

.PHONY: clean
clean:
	rm -rf build/external external

.PHONY: remove
remove:
	rm -rf $(BUILD_DIR) 

