CONFIG ?= Release
TOP_DIR = $(CURDIR)
BUILD_DIR = $(CURDIR)/build/test/$(CONFIG)

CXX = g++
CC = gcc

.PHOBY: test
test: build
	$(BUILD_DIR)/test_example; \
	$(BUILD_DIR)/test_helper; \
	$(BUILD_DIR)/test_mps; \
	$(BUILD_DIR)/test_model_component; \
	$(BUILD_DIR)/test_model; \
	$(BUILD_DIR)/test_multi_array; \
	$(BUILD_DIR)/test_neighborhood; \
	$(BUILD_DIR)/test_option; \
	$(BUILD_DIR)/test_option_enumerate; \
	$(BUILD_DIR)/test_preprocess; \
	$(BUILD_DIR)/test_solution; \
	$(BUILD_DIR)/test_utility; \
	$(BUILD_DIR)/test_utility_json; \
	$(BUILD_DIR)/test_utility_ucb1

.PHONY: build
build:
	mkdir -p $(BUILD_DIR) && \
	cd $(BUILD_DIR) && \
	cmake -DCMAKE_BUILD_TYPE=$(CONFIG) -DCMAKE_CXX_COMPILER=$(CXX) -DCMAKE_C_COMPILER=$(CC) -DTOP_DIR=$(TOP_DIR) $(TOP_DIR)/cmake/test/ && \
	cmake --build $(BUILD_DIR) 

.PHONY: remove
remove:
	rm -rf $(BUILD_DIR)

.PHONY: clean
clean:
	rm -rf build/test/

